version: 2.1

jobs:
  build:
    docker:
      - image: cimg/dotnet:8.0

    steps:
      - checkout

      - run:
          name: Display .NET Version
          command: dotnet --version

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build Application
          command: dotnet build --configuration Release --no-restore

workflows:
  build-workflow:
    jobs:
      - build